# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
# https://medium.com/@hfally/a-gitlab-ci-config-to-deploy-to-your-server-via-ssh-43bf3cf93775
image: node:latest

cache:
  paths:
    - ./client/node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  #- mkdir -p ~/.ssh
  #- ssh-keygen -R gitlab.com && ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
  #- echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  #- chmod 600 ~/.ssh/id_rsa

deploy_staging:
  stage: deploy
  script:
    - cd ./client/
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --prod --progress true
    #- cd ./dist/ && ls -la
    #- scp * edifier@app.digital-faso.tech:/httpdocs/
